@startuml

!startsub InternalConfigProviderServiceReactor
namespace score::config_management::config_daemon {
abstract class InternalConfigProviderServiceReactor{
    + {abstract} GetParameterSet(parameter_set_name : const std::string_view) : score::Result<score::cpp::pmr::string>
    --
    Responsibility: This class is interacting with ParameterSetCollection to retrieve data based on parameter_set_name.
}
}
!endsub

!startsub InternalConfigProviderServiceReactorImpl
namespace score::config_management::config_daemon {
class InternalConfigProviderServiceReactorImpl{
    + InternalConfigProviderServiceReactorImpl(\n\
    read_only_parameter_data_interface : std::shared_ptr<data_model::IReadOnlyParameterSetCollection>)
    + GetParameterSet(parameter_set_name : const std::string_view) : score::Result<score::cpp::pmr::string>
    --
    - read_only_parameter_data_interface_ : const std::shared_ptr<data_model::IReadOnlyParameterSetCollection>
}
}
!endsub

InternalConfigProviderServiceReactor <|-- InternalConfigProviderServiceReactorImpl

@enduml
